// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using channuoiProject2;

#nullable disable

namespace channuoiProject2.Migrations
{
    [DbContext(typeof(Database))]
    [Migration("20230311174637_MyFirstMigration")]
    partial class MyFirstMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("channuoiProject2.coso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Loaicoso")
                        .HasColumnType("int")
                        .HasColumnName("Loaicoso");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Name");

                    b.Property<int>("Thoigianvanhanh")
                        .HasColumnType("int")
                        .HasColumnName("Thoigianvanhanh");

                    b.HasKey("Id");

                    b.ToTable("coso");
                });

            modelBuilder.Entity("channuoiProject2.daily", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Loaidaily")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Thoigianvanhanh")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("daily");
                });

            modelBuilder.Entity("channuoiProject2.dichbenh", b =>
                {
                    b.Property<int>("DichbenhId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DichbenhId"));

                    b.Property<string>("DichbenhName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("GiaSuc")
                        .HasColumnType("int");

                    b.Property<int>("VaccinId")
                        .HasColumnType("int");

                    b.HasKey("DichbenhId");

                    b.ToTable("dichbenh");
                });

            modelBuilder.Entity("channuoiProject2.luatphap", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Loaigiayto")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("luatphap");
                });

            modelBuilder.Entity("channuoiProject2.odich", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Giasuc")
                        .HasColumnType("int");

                    b.Property<string>("OdichName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Soluowng")
                        .HasColumnType("int");

                    b.Property<string>("Vitri")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("odich");
                });

            modelBuilder.Entity("channuoiProject2.tiemphong", b =>
                {
                    b.Property<int>("VaccinId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VaccinId"));

                    b.Property<int>("OdichId")
                        .HasColumnType("int");

                    b.Property<int>("Soluongchuatien")
                        .HasColumnType("int");

                    b.Property<int>("Soluongdatiem")
                        .HasColumnType("int");

                    b.Property<int>("Thoigiantiem")
                        .HasColumnType("int");

                    b.Property<string>("VaccinName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("VaccinId");

                    b.ToTable("tiemphong");
                });

            modelBuilder.Entity("channuoiProject2.tochucvacanhan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Loaisanxuat")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Thoigianvanhanh")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("tochucvacanhan");
                });

            modelBuilder.Entity("channuoiProject2.trieutrung", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Loaisanxuat")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Thoigianvanhanh")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("trieutrung");
                });
#pragma warning restore 612, 618
        }
    }
}
